//! Emit Rust source text from a [`ModuleIR`].

use crate::CodegenError;
use crate::ir::{
    EnumIR, FieldIR, FieldKind, ModuleIR, SchemaIR, TaggedEnumIR, escape_rust_keyword, pascal_case,
};

const BANNER: &str = "\
// AUTO-GENERATED by kcl-rust-codegen — DO NOT EDIT BY HAND.
// Regenerate by re-running the codegen tool against the source KCL.
//
// Consumers that include! this file may want to wrap the include in
// a module like:
//   mod kcl_types {
//       #![allow(non_snake_case, dead_code)]
//       include!(concat!(env!(\"OUT_DIR\"), \"/generated_types.rs\"));
//   }
// so per-file lints don't bleed into the rest of their crate. The
// codegen tool intentionally does not emit #![...] attributes at the
// file root since include! places this content inside whatever scope
// the consumer chose.

";

const HELPERS: &str = r##"
/// Helper functions used by the generated `TryFrom<&ValueRef>`
/// implementations.
mod _kcl_codegen_helpers {
    use kcl_runtime::ValueRef;

    pub fn from_int(v: &ValueRef) -> Result<i64, String> {
        if v.is_int() {
            Ok(v.as_int())
        } else {
            Err(format!("expected int, got {}", v.type_str()))
        }
    }
    pub fn from_float(v: &ValueRef) -> Result<f64, String> {
        if v.is_float() {
            Ok(v.as_float())
        } else if v.is_int() {
            Ok(v.as_int() as f64)
        } else {
            Err(format!("expected float, got {}", v.type_str()))
        }
    }
    pub fn from_bool(v: &ValueRef) -> Result<bool, String> {
        if v.is_bool() {
            Ok(v.as_bool())
        } else {
            Err(format!("expected bool, got {}", v.type_str()))
        }
    }
    pub fn from_str(v: &ValueRef) -> Result<String, String> {
        if v.is_str() {
            Ok(v.as_str())
        } else {
            Err(format!("expected str, got {}", v.type_str()))
        }
    }

    // F1.6: mokkan native typed converters. Schema-validation-time
    // string coercion (F1.3) already turned any operator-written
    // string literal into a typed value before it reaches us, so
    // these accept only the corresponding Value variant. If a
    // consumer fabricates a wrong-shape ValueRef by hand they get
    // the same `expected X, got Y` error as the primitive
    // converters above.
    pub fn from_cidr(v: &ValueRef) -> Result<cidr::IpCidr, String> {
        if v.is_cidr() {
            Ok(v.as_cidr())
        } else {
            Err(format!("expected cidr, got {}", v.type_str()))
        }
    }
    pub fn from_inet(v: &ValueRef) -> Result<cidr::IpInet, String> {
        if v.is_inet() {
            Ok(v.as_inet())
        } else {
            Err(format!("expected inet, got {}", v.type_str()))
        }
    }
    pub fn from_macaddr(v: &ValueRef) -> Result<macaddr::MacAddr6, String> {
        if v.is_macaddr() {
            Ok(v.as_macaddr())
        } else {
            Err(format!("expected macaddr, got {}", v.type_str()))
        }
    }
    pub fn from_macaddr8(v: &ValueRef) -> Result<macaddr::MacAddr8, String> {
        if v.is_macaddr8() {
            Ok(v.as_macaddr8())
        } else {
            Err(format!("expected macaddr8, got {}", v.type_str()))
        }
    }
    pub fn from_ip_family(v: &ValueRef) -> Result<kcl_runtime::IpFamily, String> {
        if v.is_ip_family() {
            Ok(v.as_ip_family())
        } else {
            Err(format!("expected IpFamily, got {}", v.type_str()))
        }
    }

    // F2.7b: dispatch ValueRef → Resolvable<T>. The Pending arm
    // catches ResolvableString-shaped values (produced by symbolic
    // builtins or the F2.4 stringification/concat propagation);
    // anything else falls through to the inner T converter (the
    // eager Resolved arm).
    pub fn from_resolvable<T, F>(
        v: &ValueRef,
        conv: F,
    ) -> Result<kcl_embed::resolve::Resolvable<T>, String>
    where
        F: FnOnce(&ValueRef) -> Result<T, String>,
    {
        if let Some(rs) = kcl_embed::resolve::as_resolvable_string(v) {
            return Ok(kcl_embed::resolve::Resolvable::Pending(rs));
        }
        conv(v).map(kcl_embed::resolve::Resolvable::Resolved)
    }

    pub fn require<T, F>(
        v: &ValueRef,
        field: &str,
        parent: &str,
        conv: F,
    ) -> Result<T, String>
    where
        F: FnOnce(&ValueRef) -> Result<T, String>,
    {
        match v.dict_get_value(field) {
            Some(f) => conv(&f).map_err(|e| format!("{parent}.{field}: {e}")),
            None => Err(format!("{parent}.{field}: missing")),
        }
    }

    pub fn optional<T, F>(
        v: &ValueRef,
        field: &str,
        parent: &str,
        conv: F,
    ) -> Result<Option<T>, String>
    where
        F: FnOnce(&ValueRef) -> Result<T, String>,
    {
        match v.dict_get_value(field) {
            None => Ok(None),
            Some(f) if f.is_undefined() || f.is_none() => Ok(None),
            Some(f) => conv(&f)
                .map(Some)
                .map_err(|e| format!("{parent}.{field}: {e}")),
        }
    }

    pub fn from_list<T, F>(v: &ValueRef, mut conv: F) -> Result<Vec<T>, String>
    where
        F: FnMut(&ValueRef) -> Result<T, String>,
    {
        if !v.is_list() {
            return Err(format!("expected list, got {}", v.type_str()));
        }
        let list = v.as_list_ref();
        let mut out = Vec::with_capacity(list.values.len());
        for (i, item) in list.values.iter().enumerate() {
            out.push(conv(item).map_err(|e| format!("[{i}]: {e}"))?);
        }
        Ok(out)
    }

    pub fn from_dict<V, F>(
        v: &ValueRef,
        mut conv: F,
    ) -> Result<std::collections::HashMap<String, V>, String>
    where
        F: FnMut(&ValueRef) -> Result<V, String>,
    {
        if !v.is_dict() && !v.is_schema() {
            return Err(format!("expected dict, got {}", v.type_str()));
        }
        let dict = v.as_dict_ref();
        let mut out = std::collections::HashMap::with_capacity(dict.values.len());
        for (k, item) in dict.values.iter() {
            out.insert(
                k.clone(),
                conv(item).map_err(|e| format!("[{k:?}]: {e}"))?,
            );
        }
        Ok(out)
    }

    // F2.7c: dotted field-path constructors. Threaded by the
    // codegen-emitted walk_resolvables impls so the visitor sees
    // each Resolvable<T> slot's full path (e.g.
    // `vms.chimera1.provision[2].command`).
    pub fn join_path(prefix: &str, field: &str) -> String {
        if prefix.is_empty() {
            field.to_string()
        } else {
            format!("{prefix}.{field}")
        }
    }
    pub fn join_index_path(prefix: &str, i: usize) -> String {
        format!("{prefix}[{i}]")
    }
    pub fn join_key_path(prefix: &str, k: &str) -> String {
        format!("{prefix}[{k:?}]")
    }
}

"##;

pub(crate) fn emit_rust_source(module: &ModuleIR) -> Result<String, CodegenError> {
    let mut out = String::with_capacity(BANNER.len() + HELPERS.len() + 1024);
    out.push_str(BANNER);
    out.push_str(HELPERS);
    for e in &module.enums {
        emit_enum(&mut out, e);
    }
    for tagged in &module.tagged_enums {
        emit_tagged_enum(&mut out, tagged);
        emit_tagged_enum_try_from(&mut out, tagged);
    }
    for schema in &module.schemas {
        emit_struct(&mut out, schema);
        emit_try_from(&mut out, schema);
    }
    // F2.7c: closed `ResolvableField<'a>` enum + per-schema /
    // per-tagged-enum `walk_resolvables` impls. Skipped entirely
    // for modules without any `Resolvable<T>` field — pure-F1
    // codegen targets stay the same size and shape as before.
    let t_types = collect_module_resolvable_t_types(module);
    if !t_types.is_empty() {
        emit_resolvable_field_enum(&mut out, &t_types);
        for schema in &module.schemas {
            emit_schema_walk_resolvables(&mut out, schema, module);
        }
        for tagged in &module.tagged_enums {
            emit_tagged_walk_resolvables(&mut out, tagged, module);
        }
    }
    Ok(out)
}

// F2.7c: collect every distinct Rust type expression `T` appearing in
// a `Resolvable<T>` position across the module's schemas and tagged
// enums. The order is "first-occurrence" — stable enough for golden
// snapshots, deterministic across runs because schema/field iteration
// is deterministic.
fn collect_module_resolvable_t_types(module: &ModuleIR) -> Vec<String> {
    let mut out = Vec::new();
    for schema in &module.schemas {
        for field in &schema.fields {
            field.kind.collect_resolvable_t_rust_types(&mut out);
        }
    }
    for tagged in &module.tagged_enums {
        for variant in &tagged.variants {
            for field in &variant.fields {
                field.kind.collect_resolvable_t_rust_types(&mut out);
            }
        }
        for field in &tagged.shared_fields {
            field.kind.collect_resolvable_t_rust_types(&mut out);
        }
    }
    out
}

/// Map a `Resolvable<T>` inner-type Rust expression to a
/// PascalCase enum-variant name. Explicit table for the
/// well-known set covered by F1/F2; everything else falls back to
/// "last `::`-segment, first char uppercased". Collisions are not
/// detected here — two distinct T types that map to the same
/// variant name produce a compile error in the generated code,
/// which is the right place for the operator to discover the
/// conflict.
fn resolvable_variant_name(rust_ty: &str) -> String {
    match rust_ty {
        "String" => "Str".to_string(),
        "i64" => "Int".to_string(),
        "f64" => "Float".to_string(),
        "bool" => "Bool".to_string(),
        "cidr::IpCidr" => "Cidr".to_string(),
        "cidr::IpInet" => "Inet".to_string(),
        "macaddr::MacAddr6" => "Macaddr".to_string(),
        "macaddr::MacAddr8" => "Macaddr8".to_string(),
        "kcl_runtime::IpFamily" => "IpFamily".to_string(),
        other => {
            let last = other.rsplit("::").next().unwrap_or(other);
            let mut chars = last.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => "Unknown".to_string(),
            }
        }
    }
}

fn emit_resolvable_field_enum(out: &mut String, t_types: &[String]) {
    out.push_str("/// F2.7c: closed enum over every `Resolvable<T>` T type appearing\n");
    out.push_str("/// in this module's schemas. The codegen-emitted `walk_resolvables`\n");
    out.push_str("/// methods hand a `&mut` reference to the matching variant to the\n");
    out.push_str("/// visitor closure, so resolvers can replace `Pending(...)` with\n");
    out.push_str("/// `Resolved(...)` in place.\n");
    out.push_str("pub enum ResolvableField<'a> {\n");
    for t in t_types {
        let variant = resolvable_variant_name(t);
        out.push_str(&format!(
            "    {variant}(&'a mut kcl_embed::resolve::Resolvable<{t}>),\n"
        ));
    }
    out.push_str("}\n\n");
}

/// Whether walking a value of this kind can ever reach a
/// `Resolvable<T>`. Treats `Schema(_)` as walkable unconditionally —
/// every schema in the module gets a `walk_resolvables_at` method
/// (potentially a no-op), so calling it is always safe and the
/// caller doesn't need to track which schemas in fact contain
/// Resolvables transitively. This also dodges the cycle-detection
/// problem for mutually-recursive schemas.
fn needs_walking(kind: &FieldKind) -> bool {
    match kind {
        FieldKind::Resolvable(_) => true,
        FieldKind::List(inner) => needs_walking(inner),
        FieldKind::Dict(_, v) => needs_walking(v),
        FieldKind::Schema(_) => true,
        _ => false,
    }
}

#[derive(Clone, Copy)]
enum Bind {
    /// `binding` is a place expression of type `T` (we need `&mut <binding>`
    /// to get `&mut T`). Used at the field-access entry point —
    /// `self.foo` is Owned.
    Owned,
    /// `binding` is already an expression of type `&mut T` (from a
    /// `for (_, elem) in ...iter_mut()` loop, or from a `match &mut self`
    /// pattern destructure, or from `if let Some(inner) = &mut self.foo`).
    BorrowMut,
}

/// Emit code that walks a value of the given kind, calling `__visit`
/// for each contained `Resolvable<T>`. `binding` is the Rust
/// expression naming the value; `bind` is whether `binding` is owned
/// or `&mut`-borrowed; `path_expr` is a Rust expression of type
/// `&str` (or coerces to it) holding the field path to pass to
/// `__visit`.
fn emit_kind_walk(
    out: &mut String,
    binding: &str,
    bind: Bind,
    path_expr: &str,
    kind: &FieldKind,
    indent: &str,
) {
    match kind {
        FieldKind::Resolvable(inner) => {
            let inner_ty = inner.to_rust_type();
            let variant = resolvable_variant_name(&inner_ty);
            let arg = match bind {
                Bind::Owned => format!("&mut {binding}"),
                Bind::BorrowMut => binding.to_string(),
            };
            out.push_str(&format!(
                "{indent}__visit({path_expr}, ResolvableField::{variant}({arg}))?;\n"
            ));
        }
        FieldKind::List(inner) => {
            if !needs_walking(inner) {
                return;
            }
            out.push_str(&format!(
                "{indent}for (__i, __elem) in {binding}.iter_mut().enumerate() {{\n"
            ));
            let inner_indent = format!("{indent}    ");
            out.push_str(&format!(
                "{inner_indent}let __child_path = _kcl_codegen_helpers::join_index_path({path_expr}, __i);\n"
            ));
            emit_kind_walk(
                out,
                "__elem",
                Bind::BorrowMut,
                "&__child_path",
                inner,
                &inner_indent,
            );
            out.push_str(&format!("{indent}}}\n"));
        }
        FieldKind::Dict(_, val) => {
            if !needs_walking(val) {
                return;
            }
            out.push_str(&format!(
                "{indent}for (__k, __v) in {binding}.iter_mut() {{\n"
            ));
            let inner_indent = format!("{indent}    ");
            out.push_str(&format!(
                "{inner_indent}let __child_path = _kcl_codegen_helpers::join_key_path({path_expr}, __k);\n"
            ));
            emit_kind_walk(
                out,
                "__v",
                Bind::BorrowMut,
                "&__child_path",
                val,
                &inner_indent,
            );
            out.push_str(&format!("{indent}}}\n"));
        }
        FieldKind::Schema(_) => {
            out.push_str(&format!(
                "{indent}{binding}.walk_resolvables_at({path_expr}, __visit)?;\n"
            ));
        }
        _ => {}
    }
}

/// Emit the per-field walk fragment for a struct schema. `self.<name>`
/// is the access expression; the entry point is Owned because the
/// caller's `&mut self` is doing the borrow.
fn emit_struct_field_walk(out: &mut String, field: &FieldIR, indent: &str) {
    if !needs_walking(&field.kind) {
        return;
    }
    let binding = escape_rust_keyword(&field.name);
    let field_name = &field.name;
    let inner_indent = format!("{indent}    ");
    out.push_str(&format!("{indent}{{\n"));
    out.push_str(&format!(
        "{inner_indent}let __field_path = _kcl_codegen_helpers::join_path(__prefix, \"{field_name}\");\n"
    ));
    if field.optional && !field.has_default {
        out.push_str(&format!(
            "{inner_indent}if let Some(__inner) = &mut self.{binding} {{\n"
        ));
        let deeper_indent = format!("{inner_indent}    ");
        emit_kind_walk(
            out,
            "__inner",
            Bind::BorrowMut,
            "&__field_path",
            &field.kind,
            &deeper_indent,
        );
        out.push_str(&format!("{inner_indent}}}\n"));
    } else {
        let binding_expr = format!("self.{binding}");
        emit_kind_walk(
            out,
            &binding_expr,
            Bind::Owned,
            "&__field_path",
            &field.kind,
            &inner_indent,
        );
    }
    out.push_str(&format!("{indent}}}\n"));
}

/// Emit the per-field walk fragment for a tagged-enum variant.
/// Pattern bindings are always `&mut T` (since the match is on
/// `&mut self`), so we use BorrowMut and reach into `Option` via
/// `.as_mut()`.
fn emit_tagged_field_walk(out: &mut String, field: &FieldIR, indent: &str) {
    if !needs_walking(&field.kind) {
        return;
    }
    let binding = escape_rust_keyword(&field.name);
    let field_name = &field.name;
    let inner_indent = format!("{indent}    ");
    out.push_str(&format!("{indent}{{\n"));
    out.push_str(&format!(
        "{inner_indent}let __field_path = _kcl_codegen_helpers::join_path(__prefix, \"{field_name}\");\n"
    ));
    if field.optional && !field.has_default {
        out.push_str(&format!(
            "{inner_indent}if let Some(__inner) = {binding}.as_mut() {{\n"
        ));
        let deeper_indent = format!("{inner_indent}    ");
        emit_kind_walk(
            out,
            "__inner",
            Bind::BorrowMut,
            "&__field_path",
            &field.kind,
            &deeper_indent,
        );
        out.push_str(&format!("{inner_indent}}}\n"));
    } else {
        emit_kind_walk(
            out,
            &binding,
            Bind::BorrowMut,
            "&__field_path",
            &field.kind,
            &inner_indent,
        );
    }
    out.push_str(&format!("{indent}}}\n"));
}

fn emit_walk_resolvables_header(out: &mut String, name: &str) {
    out.push_str(&format!("impl {name} {{\n"));
    out.push_str("    /// F2.7c: visit every `Resolvable<T>` slot in this value (including\n");
    out.push_str("    /// those inside `Vec<_>`, `HashMap<_, _>`, and nested schemas /\n");
    out.push_str("    /// tagged-enum variants), passing each one to the visitor closure\n");
    out.push_str("    /// with its dotted field path. The visitor receives a `&mut\n");
    out.push_str("    /// Resolvable<T>`, so it can replace `Pending` with `Resolved` in\n");
    out.push_str("    /// place.\n");
    out.push_str("    pub fn walk_resolvables<F, E>(&mut self, mut visit: F) -> Result<(), E>\n");
    out.push_str("    where\n");
    out.push_str("        F: FnMut(&str, ResolvableField<'_>) -> Result<(), E>,\n");
    out.push_str("    {\n");
    out.push_str("        self.walk_resolvables_at(\"\", &mut visit)\n");
    out.push_str("    }\n\n");
    out.push_str("    #[doc(hidden)]\n");
    out.push_str("    pub fn walk_resolvables_at<F, E>(\n");
    out.push_str("        &mut self,\n");
    out.push_str("        __prefix: &str,\n");
    out.push_str("        __visit: &mut F,\n");
    out.push_str("    ) -> Result<(), E>\n");
    out.push_str("    where\n");
    out.push_str("        F: FnMut(&str, ResolvableField<'_>) -> Result<(), E>,\n");
    out.push_str("    {\n");
}

fn emit_schema_walk_resolvables(out: &mut String, schema: &SchemaIR, _module: &ModuleIR) {
    let any_walkable = schema.fields.iter().any(|f| needs_walking(&f.kind));
    emit_walk_resolvables_header(out, &schema.name);
    if !any_walkable {
        out.push_str("        let _ = __prefix;\n");
        out.push_str("        let _ = __visit;\n");
    } else {
        for field in &schema.fields {
            emit_struct_field_walk(out, field, "        ");
        }
    }
    out.push_str("        Ok(())\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn emit_tagged_walk_resolvables(out: &mut String, tagged: &TaggedEnumIR, _module: &ModuleIR) {
    let any_walkable = tagged
        .variants
        .iter()
        .any(|v| v.fields.iter().any(|f| needs_walking(&f.kind)))
        || tagged.shared_fields.iter().any(|f| needs_walking(&f.kind));
    emit_walk_resolvables_header(out, &tagged.name);
    if !any_walkable {
        out.push_str("        let _ = __prefix;\n");
        out.push_str("        let _ = __visit;\n");
        out.push_str("        Ok(())\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
        return;
    }
    out.push_str("        match self {\n");
    for variant in &tagged.variants {
        let all_fields: Vec<&FieldIR> = variant
            .fields
            .iter()
            .chain(tagged.shared_fields.iter())
            .collect();
        let walkable: Vec<&FieldIR> = all_fields
            .iter()
            .copied()
            .filter(|f| needs_walking(&f.kind))
            .collect();
        if walkable.is_empty() {
            out.push_str(&format!(
                "            {}::{} {{ .. }} => {{}}\n",
                tagged.name, variant.rust_name
            ));
        } else {
            let pattern_fields: Vec<String> = walkable
                .iter()
                .map(|f| escape_rust_keyword(&f.name))
                .collect();
            out.push_str(&format!(
                "            {}::{} {{ {}, .. }} => {{\n",
                tagged.name,
                variant.rust_name,
                pattern_fields.join(", ")
            ));
            for field in &walkable {
                emit_tagged_field_walk(out, field, "                ");
            }
            out.push_str("            }\n");
        }
    }
    out.push_str("        }\n");
    out.push_str("        Ok(())\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn emit_enum(out: &mut String, e: &EnumIR) {
    out.push_str(&format!(
        "/// Generated from {} — lifted from a KCL string-literal union.\n",
        e.origin
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n");
    out.push_str(&format!("pub enum {} {{\n", e.rust_name));
    for variant in &e.variants {
        out.push_str(&format!("    /// KCL source literal: {variant:?}\n"));
        out.push_str(&format!("    {},\n", pascal_case(variant)));
    }
    out.push_str("}\n\n");

    // TryFrom<&ValueRef>: matches on the string content; rejects
    // anything that isn't one of the declared literals.
    out.push_str(&format!(
        "impl TryFrom<&kcl_runtime::ValueRef> for {} {{\n",
        e.rust_name
    ));
    out.push_str("    type Error = String;\n");
    out.push_str("    fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {\n");
    out.push_str("        if !v.is_str() {\n");
    out.push_str(&format!(
        "            return Err(format!(\"expected str for {}, got {{}}\", v.type_str()));\n",
        e.rust_name
    ));
    out.push_str("        }\n");
    out.push_str("        match v.as_str().as_str() {\n");
    for variant in &e.variants {
        out.push_str(&format!(
            "            {:?} => Ok({}::{}),\n",
            variant,
            e.rust_name,
            pascal_case(variant)
        ));
    }
    // Build the expected-list literal with each variant wrapped in
    // escaped quotes so the generated Rust source compiles. (Naively
    // interpolating `{:?}` on a Vec<String> produces unescaped
    // double-quotes inside the surrounding string literal.)
    let expected_list = e
        .variants
        .iter()
        .map(|v| format!("\\\"{v}\\\""))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "            other => Err(format!(\"unexpected {} literal {{other:?}}; expected one of [{expected_list}]\")),\n",
        e.rust_name
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn emit_struct(out: &mut String, schema: &SchemaIR) {
    if !schema.doc.is_empty() {
        for line in schema.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "/// Generated from `{}` (line {})\n",
        schema.source_file, schema.source_line
    ));
    // PartialEq on f64 is NaN-aware: `f64::NAN != f64::NAN`. For
    // schemas with float fields this is the standard Rust behaviour,
    // but worth flagging in the generated rustdoc so consumers
    // aren't surprised when two `Vm`s with NaN field values compare
    // unequal. (Future evolution: conditional derive or custom impl
    // — out of MVP scope; tracked under Phase 4B.)
    let has_float = schema.fields.iter().any(|f| f.kind.contains_float());
    if has_float {
        out.push_str("/// **Note:** this type contains `f64` field(s); the derived\n");
        out.push_str("/// `PartialEq` is NaN-aware (`f64::NAN != f64::NAN`). Two\n");
        out.push_str("/// instances with NaN field values will compare unequal.\n");
    }
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub struct {} {{\n", schema.name));
    for field in &schema.fields {
        if field.has_default {
            out.push_str(
                "    /// Has a default value in the source schema; the KCL VM populates it\n",
            );
            out.push_str("    /// during evaluation, so this field is always present in the\n");
            out.push_str("    /// resulting `ValueRef`.\n");
        }
        let rust_ty = field.kind.to_rust_type();
        // `field?: T = default` (optional WITH a default) emits as
        // `T`, not `Option<T>`: the KCL VM populates the default
        // during evaluation, so the field is always present in
        // the resulting `ValueRef`. Honours the existing rustdoc
        // contract on `has_default` ("always present in the
        // resulting ValueRef") that pre-fix-emit didn't actually
        // enforce.
        let rust_ty = if field.optional && !field.has_default {
            format!("Option<{rust_ty}>")
        } else {
            rust_ty
        };
        out.push_str(&format!(
            "    pub {}: {},\n",
            escape_rust_keyword(&field.name),
            rust_ty
        ));
    }
    out.push_str("}\n\n");
}

fn emit_try_from(out: &mut String, schema: &SchemaIR) {
    let name = &schema.name;
    out.push_str(&format!(
        "impl TryFrom<&kcl_runtime::ValueRef> for {name} {{\n"
    ));
    out.push_str("    type Error = String;\n");
    out.push_str(
        "    /// In a well-formed deployment where (a) codegen was run against the same\n",
    );
    out.push_str(
        "    /// schema source the VM was given, and (b) the VM successfully evaluated the\n",
    );
    out.push_str(
        "    /// user program against that schema, the `Err` branch is unreachable: the\n",
    );
    out.push_str(
        "    /// VM would have rejected the input before producing a `ValueRef` that fails\n",
    );
    out.push_str(
        "    /// this conversion. The `Result` is a typed seatbelt against codegen drift\n",
    );
    out.push_str(
        "    /// and VM bugs, not a control-flow surface — prefer `.expect(\"VM produced\n",
    );
    out.push_str("    /// schema-conformant value\")` over propagating the error.\n");
    out.push_str("    fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {\n");
    out.push_str("        if !v.is_dict() && !v.is_schema() {\n");
    out.push_str(&format!(
        "            return Err(format!(\"expected {name} dict/schema, got {{}}\", v.type_str()));\n"
    ));
    out.push_str("        }\n");
    for field in &schema.fields {
        emit_field_read(out, name, field);
    }
    out.push_str(&format!("        Ok({name} {{\n"));
    for field in &schema.fields {
        out.push_str(&format!(
            "            {},\n",
            escape_rust_keyword(&field.name)
        ));
    }
    out.push_str("        })\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

/// Emit a Rust `enum TaggedX { ... }` definition from a
/// [`TaggedEnumIR`]. Each variant has its assigned fields plus the
/// `shared_fields` from the parent. The discriminator field itself
/// is NOT emitted — the variant tag encodes it.
fn emit_tagged_enum(out: &mut String, tagged: &TaggedEnumIR) {
    if !tagged.doc.is_empty() {
        for line in tagged.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "/// Generated from `{}` (line {}) — tagged enum lifted via `# @rust: tagged_enum(discriminator = {:?})`.\n",
        tagged.source_file, tagged.source_line, tagged.discriminator,
    ));
    let has_float = tagged
        .variants
        .iter()
        .flat_map(|v| v.fields.iter())
        .chain(tagged.shared_fields.iter())
        .any(|f| f.kind.contains_float());
    if has_float {
        out.push_str("/// **Note:** this enum contains `f64` field(s); the derived\n");
        out.push_str("/// `PartialEq` is NaN-aware (`f64::NAN != f64::NAN`).\n");
    }
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {} {{\n", tagged.name));
    for variant in &tagged.variants {
        out.push_str(&format!(
            "    /// KCL discriminator literal: {:?}\n",
            variant.kcl_literal,
        ));
        out.push_str(&format!("    {} {{\n", variant.rust_name));
        // Variant-assigned fields first, then shared fields. Stable
        // ordering matters for pattern-match ergonomics — variant
        // fields are what's "interesting" per variant.
        for field in &variant.fields {
            emit_variant_field_decl(out, field);
        }
        for field in &tagged.shared_fields {
            emit_variant_field_decl(out, field);
        }
        out.push_str("    },\n");
    }
    out.push_str("}\n\n");
}

fn emit_variant_field_decl(out: &mut String, field: &FieldIR) {
    if field.has_default {
        out.push_str(
            "        /// Has a default value in the source schema; populated by the KCL VM.\n",
        );
    }
    let rust_ty = field.kind.to_rust_type();
    // See `emit_field_decl`: `optional && !has_default` is the true
    // "user can omit AND VM won't fill it in" case. Defaulted
    // optionals stay as `T`.
    let rust_ty = if field.optional && !field.has_default {
        format!("Option<{rust_ty}>")
    } else {
        rust_ty
    };
    out.push_str(&format!(
        "        {}: {},\n",
        escape_rust_keyword(&field.name),
        rust_ty,
    ));
}

/// Emit `impl TryFrom<&ValueRef> for TaggedX`. Reads the
/// discriminator field, dispatches on its string value, reads each
/// variant's assigned + shared fields, constructs the matching
/// variant.
fn emit_tagged_enum_try_from(out: &mut String, tagged: &TaggedEnumIR) {
    let name = &tagged.name;
    let discriminator = &tagged.discriminator;

    out.push_str(&format!(
        "impl TryFrom<&kcl_runtime::ValueRef> for {name} {{\n"
    ));
    out.push_str("    type Error = String;\n");
    out.push_str(
        "    /// In a well-formed deployment where (a) codegen was run against the same\n",
    );
    out.push_str(
        "    /// schema source the VM was given, and (b) the VM successfully evaluated the\n",
    );
    out.push_str(
        "    /// user program against that schema (including its `check:` block predicates\n",
    );
    out.push_str(
        "    /// enforcing per-variant required fields), the `Err` branch is unreachable.\n",
    );
    out.push_str("    fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {\n");
    out.push_str("        if !v.is_dict() && !v.is_schema() {\n");
    out.push_str(&format!(
        "            return Err(format!(\"expected {name} dict/schema, got {{}}\", v.type_str()));\n"
    ));
    out.push_str("        }\n");
    // Read discriminator string from the dict.
    out.push_str(&format!(
        "        let __disc = _kcl_codegen_helpers::require(v, \"{discriminator}\", \"{name}\", _kcl_codegen_helpers::from_str)?;\n"
    ));
    out.push_str("        match __disc.as_str() {\n");
    for variant in &tagged.variants {
        let variant_parent = format!("{}::{}", name, variant.rust_name);
        out.push_str(&format!("            {:?} => {{\n", variant.kcl_literal));
        for field in &variant.fields {
            emit_variant_field_read(out, &variant_parent, field);
        }
        for field in &tagged.shared_fields {
            emit_variant_field_read(out, &variant_parent, field);
        }
        out.push_str(&format!(
            "                Ok({}::{} {{\n",
            name, variant.rust_name,
        ));
        for field in &variant.fields {
            out.push_str(&format!(
                "                    {},\n",
                escape_rust_keyword(&field.name),
            ));
        }
        for field in &tagged.shared_fields {
            out.push_str(&format!(
                "                    {},\n",
                escape_rust_keyword(&field.name),
            ));
        }
        out.push_str("                })\n");
        out.push_str("            }\n");
    }
    let expected_list = tagged
        .variants
        .iter()
        .map(|v| format!("\\\"{}\\\"", v.kcl_literal))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "            other => Err(format!(\"unexpected {name}.{discriminator} literal {{other:?}}; expected one of [{expected_list}]\")),\n"
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn emit_variant_field_read(out: &mut String, parent: &str, field: &FieldIR) {
    let conv = emit_conv_closure(&field.kind);
    let binding = escape_rust_keyword(&field.name);
    let indent = "                ";
    // `optional && !has_default` matches the field-type branch in
    // `emit_variant_field_decl` — defaulted optionals are emitted
    // as `T` (not `Option<T>`), so the read site has to use
    // `require` rather than `optional`. Keep the two branches in
    // sync; a mismatch produces type-confusion compile errors in
    // the generated code.
    if field.optional && !field.has_default {
        out.push_str(&format!(
            "{indent}let {binding} = _kcl_codegen_helpers::optional(v, \"{}\", \"{}\", {})?;\n",
            field.name, parent, conv,
        ));
    } else {
        out.push_str(&format!(
            "{indent}let {binding} = _kcl_codegen_helpers::require(v, \"{}\", \"{}\", {})?;\n",
            field.name, parent, conv,
        ));
    }
}

fn emit_field_read(out: &mut String, parent: &str, field: &FieldIR) {
    let conv = emit_conv_closure(&field.kind);
    let binding = escape_rust_keyword(&field.name);
    // See `emit_variant_field_read` for the rationale on the
    // `&& !field.has_default` clause.
    if field.optional && !field.has_default {
        out.push_str(&format!(
            "        let {} = _kcl_codegen_helpers::optional(v, \"{}\", \"{}\", {})?;\n",
            binding, field.name, parent, conv
        ));
    } else {
        out.push_str(&format!(
            "        let {} = _kcl_codegen_helpers::require(v, \"{}\", \"{}\", {})?;\n",
            binding, field.name, parent, conv
        ));
    }
}

fn emit_conv_closure(kind: &FieldKind) -> String {
    match kind {
        FieldKind::Int => "_kcl_codegen_helpers::from_int".to_string(),
        FieldKind::Float => "_kcl_codegen_helpers::from_float".to_string(),
        FieldKind::Bool => "_kcl_codegen_helpers::from_bool".to_string(),
        FieldKind::Str => "_kcl_codegen_helpers::from_str".to_string(),
        FieldKind::List(inner) => {
            let inner_conv = emit_conv_closure(inner);
            format!("|f: &kcl_runtime::ValueRef| _kcl_codegen_helpers::from_list(f, {inner_conv})")
        }
        FieldKind::Dict(_key, val) => {
            let val_conv = emit_conv_closure(val);
            format!("|f: &kcl_runtime::ValueRef| _kcl_codegen_helpers::from_dict(f, {val_conv})")
        }
        FieldKind::Schema(name) => {
            format!(
                "|f: &kcl_runtime::ValueRef| <{name} as TryFrom<&kcl_runtime::ValueRef>>::try_from(f)"
            )
        }
        FieldKind::StrEnum(name) => {
            format!(
                "|f: &kcl_runtime::ValueRef| <{name} as TryFrom<&kcl_runtime::ValueRef>>::try_from(f)"
            )
        }
        FieldKind::Cidr => "_kcl_codegen_helpers::from_cidr".to_string(),
        FieldKind::Inet => "_kcl_codegen_helpers::from_inet".to_string(),
        FieldKind::Macaddr => "_kcl_codegen_helpers::from_macaddr".to_string(),
        FieldKind::Macaddr8 => "_kcl_codegen_helpers::from_macaddr8".to_string(),
        FieldKind::IpFamily => "_kcl_codegen_helpers::from_ip_family".to_string(),
        FieldKind::Resolvable(inner) => {
            // F2.7b: dispatch on `is_resolvable_string` first
            // (Pending arm), fall through to the inner T's
            // conversion (Resolved arm). The inner conversion
            // closure is the same one any non-RS field would use,
            // wrapped in `Resolvable::Resolved(...)`.
            let inner_conv = emit_conv_closure(inner);
            format!(
                "|f: &kcl_runtime::ValueRef| _kcl_codegen_helpers::from_resolvable(f, {inner_conv})"
            )
        }
        FieldKind::Unsupported(label) => {
            format!("compile_error!(\"unsupported field kind: {label}\")")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{FieldIR, TaggedEnumIR, TaggedEnumVariantIR};

    fn schema_ir_for(name: &str, fields: Vec<FieldIR>) -> SchemaIR {
        SchemaIR {
            name: name.to_string(),
            source_file: "test.k".to_string(),
            source_line: 0,
            fields,
            doc: String::new(),
            annotations: Default::default(),
        }
    }

    fn module_with_schemas(schemas: Vec<SchemaIR>) -> ModuleIR {
        ModuleIR {
            schemas,
            enums: Vec::new(),
            tagged_enums: Vec::new(),
        }
    }

    #[test]
    fn emit_primitive_struct() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Vm",
            vec![
                FieldIR {
                    name: "name".into(),
                    kind: FieldKind::Str,
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "memory_mb".into(),
                    kind: FieldKind::Int,
                    optional: false,
                    has_default: true,
                },
                FieldIR {
                    name: "notes".into(),
                    kind: FieldKind::Str,
                    optional: true,
                    has_default: false,
                },
                // The defaulted-optional case (`field?: T = default`
                // in KCL): pre-fix this was emitted as `Option<T>`,
                // forcing consumers to `.unwrap_or(default)` at every
                // access site. The KCL VM populates the default
                // during evaluation, so the field is always present
                // in the `ValueRef` — codegen collapses it to plain
                // `T`. Pinned here so a future regression flips the
                // emission back without anyone noticing.
                FieldIR {
                    name: "sudo".into(),
                    kind: FieldKind::Bool,
                    optional: true,
                    has_default: true,
                },
            ],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(out.contains("pub struct Vm {"));
        assert!(out.contains("pub name: String,"));
        assert!(out.contains("pub memory_mb: i64,"));
        assert!(out.contains("pub notes: Option<String>,"));
        // Defaulted-optional emits as plain `T`, not `Option<T>`,
        // and the TryFrom reads it via `require` (not `optional`)
        // because the VM guarantees the field is always present.
        assert!(out.contains("pub sudo: bool,"));
        assert!(
            out.contains("let sudo = _kcl_codegen_helpers::require(v, \"sudo\""),
            "defaulted-optional field should use `require`, not `optional`:\n{out}"
        );
        assert!(out.contains("impl TryFrom<&kcl_runtime::ValueRef> for Vm"));
    }

    #[test]
    fn emit_str_enum_and_field() {
        let mut module = module_with_schemas(vec![schema_ir_for(
            "TestAssertion",
            vec![FieldIR {
                name: "type".into(),
                kind: FieldKind::StrEnum("TestAssertionType".into()),
                optional: false,
                has_default: false,
            }],
        )]);
        module.enums.push(EnumIR {
            rust_name: "TestAssertionType".into(),
            variants: vec!["command".into(), "service".into(), "port".into()],
            origin: "TestAssertion.type".into(),
        });
        let out = emit_rust_source(&module).expect("emit");
        // Enum definition
        assert!(out.contains("pub enum TestAssertionType {"));
        assert!(out.contains("    Command,"));
        assert!(out.contains("    Service,"));
        assert!(out.contains("    Port,"));
        // Enum TryFrom matches the literals
        assert!(out.contains("\"command\" => Ok(TestAssertionType::Command),"));
        // Struct field uses the enum type
        assert!(out.contains("pub r#type: TestAssertionType,"));
        // Struct TryFrom delegates to enum's TryFrom
        assert!(
            out.contains("<TestAssertionType as TryFrom<&kcl_runtime::ValueRef>>::try_from(f)")
        );
    }

    #[test]
    fn escape_rust_keyword_field_names() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Foo",
            vec![FieldIR {
                name: "type".into(),
                kind: FieldKind::Str,
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(out.contains("pub r#type: String,"));
        assert!(out.contains("let r#type = _kcl_codegen_helpers::require(v, \"type\""));
    }

    /// F1.6 — mokkan typed-inet fields codegen straight through to
    /// the upstream `cidr` / `macaddr` crate types and our own
    /// `kcl_runtime::IpFamily` enum. The TryFrom bodies delegate to
    /// the `_kcl_codegen_helpers::from_<type>` wrappers — same
    /// shape as `from_int` / `from_str` etc.
    #[test]
    fn emit_mokkan_typed_inet_fields() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Network",
            vec![
                FieldIR {
                    name: "cidr".into(),
                    kind: FieldKind::Cidr,
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "gateway".into(),
                    kind: FieldKind::Inet,
                    optional: true,
                    has_default: false,
                },
                FieldIR {
                    name: "mac".into(),
                    kind: FieldKind::Macaddr,
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "eui64".into(),
                    kind: FieldKind::Macaddr8,
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "family".into(),
                    kind: FieldKind::IpFamily,
                    optional: false,
                    has_default: false,
                },
            ],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        // Struct fields use the typed Rust types.
        assert!(
            out.contains("pub cidr: cidr::IpCidr,"),
            "missing typed cidr field:\n{out}"
        );
        assert!(
            out.contains("pub gateway: Option<cidr::IpInet>,"),
            "missing typed inet field:\n{out}"
        );
        assert!(
            out.contains("pub mac: macaddr::MacAddr6,"),
            "missing typed macaddr field:\n{out}"
        );
        assert!(
            out.contains("pub eui64: macaddr::MacAddr8,"),
            "missing typed macaddr8 field:\n{out}"
        );
        assert!(
            out.contains("pub family: kcl_runtime::IpFamily,"),
            "missing IpFamily field:\n{out}"
        );
        // TryFrom bodies use the typed converters.
        assert!(out.contains("_kcl_codegen_helpers::from_cidr"));
        assert!(out.contains("_kcl_codegen_helpers::from_inet"));
        assert!(out.contains("_kcl_codegen_helpers::from_macaddr"));
        assert!(out.contains("_kcl_codegen_helpers::from_macaddr8"));
        assert!(out.contains("_kcl_codegen_helpers::from_ip_family"));
    }

    /// F1.6 — collection shapes (`[cidr]`, `{str:inet}`) round-trip
    /// the typed inner kind through the same `from_list` /
    /// `from_dict` machinery the rest of the codegen uses.
    #[test]
    fn emit_mokkan_typed_inet_in_collections() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Pool",
            vec![
                FieldIR {
                    name: "subnets".into(),
                    kind: FieldKind::List(Box::new(FieldKind::Cidr)),
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "by_name".into(),
                    kind: FieldKind::Dict(Box::new(FieldKind::Str), Box::new(FieldKind::Inet)),
                    optional: false,
                    has_default: false,
                },
            ],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("pub subnets: Vec<cidr::IpCidr>,"),
            "list of cidr:\n{out}"
        );
        assert!(
            out.contains("pub by_name: std::collections::HashMap<String, cidr::IpInet>,"),
            "dict of inet:\n{out}"
        );
    }

    /// F2.7b — `T | ResolvableString` field emits as
    /// `kcl_embed::resolve::Resolvable<T>` with TryFrom body using
    /// `from_resolvable` to dispatch on the Pending arm before
    /// falling through to the inner T conversion.
    #[test]
    fn emit_resolvable_string_field_emits_resolvable_t() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Cfg",
            vec![
                FieldIR {
                    name: "command".into(),
                    kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "subnet".into(),
                    kind: FieldKind::Resolvable(Box::new(FieldKind::Cidr)),
                    optional: false,
                    has_default: false,
                },
            ],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("pub command: kcl_embed::resolve::Resolvable<String>,"),
            "Resolvable<String> field:\n{out}"
        );
        assert!(
            out.contains("pub subnet: kcl_embed::resolve::Resolvable<cidr::IpCidr>,"),
            "Resolvable<IpCidr> field:\n{out}"
        );
        // TryFrom body dispatches via from_resolvable wrapping the
        // inner T converter.
        assert!(
            out.contains("_kcl_codegen_helpers::from_resolvable"),
            "TryFrom body should use from_resolvable:\n{out}"
        );
    }

    /// F2.7b — collection shape `[T | ResolvableString]` emits as
    /// `Vec<Resolvable<T>>`. The Resolvable layer goes on the
    /// inner element type, not the collection itself.
    #[test]
    fn emit_resolvable_string_in_list_emits_vec_of_resolvable_t() {
        let module = module_with_schemas(vec![schema_ir_for(
            "ProvisionStep",
            vec![FieldIR {
                name: "inline".into(),
                kind: FieldKind::List(Box::new(FieldKind::Resolvable(Box::new(FieldKind::Str)))),
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("pub inline: Vec<kcl_embed::resolve::Resolvable<String>>,"),
            "Vec<Resolvable<String>>:\n{out}"
        );
    }

    /// F2.7b — collection shape `{str: T | ResolvableString}` emits
    /// as `HashMap<String, Resolvable<T>>`. Same Resolvable-inner
    /// shape as the list case.
    #[test]
    fn emit_resolvable_string_in_dict_emits_hashmap_of_resolvable_t() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Tags",
            vec![FieldIR {
                name: "labels".into(),
                kind: FieldKind::Dict(
                    Box::new(FieldKind::Str),
                    Box::new(FieldKind::Resolvable(Box::new(FieldKind::Str))),
                ),
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains(
                "pub labels: std::collections::HashMap<String, kcl_embed::resolve::Resolvable<String>>,"
            ),
            "HashMap<String, Resolvable<String>>:\n{out}"
        );
    }

    /// F2.7c — well-known variant-name mappings stay stable. The
    /// fallback path (last `::` segment, first char uppercased) is
    /// exercised here too so the open-set behaviour is pinned.
    #[test]
    fn resolvable_variant_name_mappings() {
        assert_eq!(resolvable_variant_name("String"), "Str");
        assert_eq!(resolvable_variant_name("i64"), "Int");
        assert_eq!(resolvable_variant_name("f64"), "Float");
        assert_eq!(resolvable_variant_name("bool"), "Bool");
        assert_eq!(resolvable_variant_name("cidr::IpCidr"), "Cidr");
        assert_eq!(resolvable_variant_name("cidr::IpInet"), "Inet");
        assert_eq!(resolvable_variant_name("macaddr::MacAddr6"), "Macaddr");
        assert_eq!(resolvable_variant_name("macaddr::MacAddr8"), "Macaddr8");
        assert_eq!(resolvable_variant_name("kcl_runtime::IpFamily"), "IpFamily");
        // Fallback: unknown last-segment, first char already upper.
        assert_eq!(resolvable_variant_name("foo::Quux"), "Quux");
        // Fallback: unknown last-segment, first char lower.
        assert_eq!(resolvable_variant_name("foo::quux"), "Quux");
    }

    /// F2.7c — modules without any `Resolvable<T>` field don't get
    /// the `ResolvableField` enum or any `walk_resolvables` impls.
    /// Pure-F1 codegen targets stay the same shape as before.
    #[test]
    fn no_walker_emitted_for_pure_eager_module() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Vm",
            vec![FieldIR {
                name: "name".into(),
                kind: FieldKind::Str,
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            !out.contains("pub enum ResolvableField"),
            "no Resolvable means no enum:\n{out}"
        );
        // The HELPERS comment references walk_resolvables, so look
        // for the actual fn declaration instead of a bare substring.
        assert!(
            !out.contains("pub fn walk_resolvables"),
            "no Resolvable means no walker:\n{out}"
        );
    }

    /// F2.7c — a single `Resolvable<String>` field gets a walker
    /// that calls `__visit` exactly once with the field path
    /// `"command"`.
    #[test]
    fn walker_visits_single_resolvable_field() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Cfg",
            vec![FieldIR {
                name: "command".into(),
                kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        // Closed enum has exactly the one variant.
        assert!(
            out.contains("pub enum ResolvableField<'a> {"),
            "ResolvableField enum:\n{out}"
        );
        assert!(
            out.contains("Str(&'a mut kcl_embed::resolve::Resolvable<String>)"),
            "Str variant:\n{out}"
        );
        // Walker shape.
        assert!(out.contains("impl Cfg {"), "walker impl block:\n{out}");
        assert!(
            out.contains("pub fn walk_resolvables<F, E>"),
            "walk_resolvables fn:\n{out}"
        );
        assert!(
            out.contains("pub fn walk_resolvables_at<F, E>"),
            "walk_resolvables_at fn:\n{out}"
        );
        // Visit call uses the field path.
        assert!(
            out.contains(
                "let __field_path = _kcl_codegen_helpers::join_path(__prefix, \"command\");"
            ),
            "field path constructed:\n{out}"
        );
        assert!(
            out.contains("__visit(&__field_path, ResolvableField::Str(&mut self.command))?;"),
            "visit call:\n{out}"
        );
    }

    /// F2.7c — `Optional<Resolvable<T>>` walks only when `Some(_)`.
    /// Wraps the visit call in an `if let Some(__inner) = &mut
    /// self.<name>`.
    #[test]
    fn walker_handles_optional_resolvable() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Cfg",
            vec![FieldIR {
                name: "script".into(),
                kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                optional: true,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("if let Some(__inner) = &mut self.script {"),
            "optional unwrap:\n{out}"
        );
        assert!(
            out.contains("__visit(&__field_path, ResolvableField::Str(__inner))?;"),
            "visit on unwrapped inner:\n{out}"
        );
    }

    /// F2.7c — `Vec<Resolvable<T>>` iterates with index, building
    /// `path[i]` child paths via the join_index_path helper.
    #[test]
    fn walker_iterates_list_of_resolvable() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Step",
            vec![FieldIR {
                name: "inline".into(),
                kind: FieldKind::List(Box::new(FieldKind::Resolvable(Box::new(FieldKind::Str)))),
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("for (__i, __elem) in self.inline.iter_mut().enumerate() {"),
            "list loop:\n{out}"
        );
        assert!(
            out.contains(
                "let __child_path = _kcl_codegen_helpers::join_index_path(&__field_path, __i);"
            ),
            "index path:\n{out}"
        );
        assert!(
            out.contains("__visit(&__child_path, ResolvableField::Str(__elem))?;"),
            "visit on borrowed elem:\n{out}"
        );
    }

    /// F2.7c — `HashMap<_, Resolvable<T>>` iterates with key,
    /// building `path[k]` child paths via the join_key_path helper.
    #[test]
    fn walker_iterates_dict_of_resolvable() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Tags",
            vec![FieldIR {
                name: "labels".into(),
                kind: FieldKind::Dict(
                    Box::new(FieldKind::Str),
                    Box::new(FieldKind::Resolvable(Box::new(FieldKind::Str))),
                ),
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("for (__k, __v) in self.labels.iter_mut() {"),
            "dict loop:\n{out}"
        );
        assert!(
            out.contains(
                "let __child_path = _kcl_codegen_helpers::join_key_path(&__field_path, __k);"
            ),
            "key path:\n{out}"
        );
        assert!(
            out.contains("__visit(&__child_path, ResolvableField::Str(__v))?;"),
            "visit on borrowed value:\n{out}"
        );
    }

    /// F2.7c — nested schema fields recurse into the inner schema's
    /// own `walk_resolvables_at` with the dotted field path passed
    /// down. The inner schema's walker may itself be a no-op (if it
    /// has no Resolvables), but the call is uniformly emitted so the
    /// outer codegen doesn't need to know.
    #[test]
    fn walker_recurses_into_nested_schemas() {
        let mut module = module_with_schemas(vec![
            schema_ir_for(
                "Vm",
                vec![FieldIR {
                    name: "provision".into(),
                    kind: FieldKind::Schema("ProvisionStep".into()),
                    optional: false,
                    has_default: false,
                }],
            ),
            schema_ir_for(
                "ProvisionStep",
                vec![FieldIR {
                    name: "command".into(),
                    kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                    optional: false,
                    has_default: false,
                }],
            ),
        ]);
        // Vm itself has no Resolvable; the module-wide collector
        // picks ProvisionStep.command's Resolvable<String> up.
        let out = emit_rust_source(&mut module).expect("emit");
        assert!(out.contains("impl Vm {"), "Vm walker impl block:\n{out}");
        assert!(
            out.contains("self.provision.walk_resolvables_at(&__field_path, __visit)?;"),
            "recurses into nested schema:\n{out}"
        );
        assert!(
            out.contains("impl ProvisionStep {"),
            "ProvisionStep walker impl block:\n{out}"
        );
    }

    /// F2.7c — schemas with no Resolvable fields in a module that DOES
    /// have Resolvables get an empty no-op walker. Catches the
    /// dead-code variable case (must use `let _ = __prefix; let _ =
    /// __visit;` to suppress the unused warning).
    #[test]
    fn walker_emits_no_op_for_resolvable_free_schemas() {
        let module = module_with_schemas(vec![
            schema_ir_for(
                "Plain",
                vec![FieldIR {
                    name: "name".into(),
                    kind: FieldKind::Str,
                    optional: false,
                    has_default: false,
                }],
            ),
            schema_ir_for(
                "Cfg",
                vec![FieldIR {
                    name: "command".into(),
                    kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                    optional: false,
                    has_default: false,
                }],
            ),
        ]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("impl Plain {"),
            "no-op walker still emitted:\n{out}"
        );
        // Empty body: `let _ = __prefix; let _ = __visit;`.
        let plain_section = out
            .split("impl Plain {")
            .nth(1)
            .and_then(|s| s.split("impl ").next())
            .unwrap_or("");
        assert!(
            plain_section.contains("let _ = __prefix;"),
            "no-op suppression: __prefix unused:\n{plain_section}"
        );
        assert!(
            plain_section.contains("let _ = __visit;"),
            "no-op suppression: __visit unused:\n{plain_section}"
        );
    }

    /// F2.7c — `ResolvableField` enum collects across all schemas
    /// in the module, deduplicated. Two schemas with the same T
    /// produce one variant; two schemas with different Ts produce
    /// two variants in first-occurrence order.
    #[test]
    fn resolvable_field_enum_dedupes_across_schemas() {
        let module = module_with_schemas(vec![
            schema_ir_for(
                "A",
                vec![FieldIR {
                    name: "x".into(),
                    kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                    optional: false,
                    has_default: false,
                }],
            ),
            schema_ir_for(
                "B",
                vec![
                    FieldIR {
                        name: "y".into(),
                        kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                        optional: false,
                        has_default: false,
                    },
                    FieldIR {
                        name: "z".into(),
                        kind: FieldKind::Resolvable(Box::new(FieldKind::Cidr)),
                        optional: false,
                        has_default: false,
                    },
                ],
            ),
        ]);
        let out = emit_rust_source(&module).expect("emit");
        // Exactly one Str variant despite two Resolvable<String> fields.
        let str_variant_count = out
            .matches("Str(&'a mut kcl_embed::resolve::Resolvable<String>)")
            .count();
        assert_eq!(str_variant_count, 1, "deduped Str:\n{out}");
        assert!(
            out.contains("Cidr(&'a mut kcl_embed::resolve::Resolvable<cidr::IpCidr>)"),
            "Cidr variant present:\n{out}"
        );
        // First-occurrence order: Str (from A.x) precedes Cidr (from B.z).
        let str_idx = out.find("Str(&'a mut").expect("Str variant present");
        let cidr_idx = out.find("Cidr(&'a mut").expect("Cidr variant present");
        assert!(
            str_idx < cidr_idx,
            "first-occurrence order Str before Cidr:\n{out}"
        );
    }

    /// F2.7c — tagged enum variants pattern-destructure and walk
    /// each variant's Resolvable fields. Other variants are
    /// matched-but-skipped with `_ => {}`. (ProvisionStep is the
    /// concrete Tilley case driving this.)
    #[test]
    fn walker_handles_tagged_enum_variants() {
        let module = ModuleIR {
            schemas: Vec::new(),
            enums: Vec::new(),
            tagged_enums: vec![TaggedEnumIR {
                name: "ProvisionStep".into(),
                source_file: "core.k".into(),
                source_line: 0,
                doc: String::new(),
                discriminator: "type".into(),
                shared_fields: Vec::new(),
                variants: vec![
                    TaggedEnumVariantIR {
                        rust_name: "Inline".into(),
                        kcl_literal: "inline".into(),
                        fields: vec![FieldIR {
                            name: "inline".into(),
                            kind: FieldKind::List(Box::new(FieldKind::Resolvable(Box::new(
                                FieldKind::Str,
                            )))),
                            optional: false,
                            has_default: false,
                        }],
                    },
                    TaggedEnumVariantIR {
                        rust_name: "Script".into(),
                        kcl_literal: "script".into(),
                        fields: vec![FieldIR {
                            name: "script".into(),
                            kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                            optional: false,
                            has_default: false,
                        }],
                    },
                ],
            }],
        };
        let out = emit_rust_source(&module).expect("emit");
        assert!(
            out.contains("impl ProvisionStep {"),
            "tagged enum walker impl:\n{out}"
        );
        // Inline variant: destructure `inline`, iterate over the list.
        assert!(
            out.contains("ProvisionStep::Inline { inline, .. } => {"),
            "Inline variant destructure:\n{out}"
        );
        assert!(
            out.contains("for (__i, __elem) in inline.iter_mut().enumerate() {"),
            "Inline iter_mut:\n{out}"
        );
        // Script variant: destructure `script` (already &mut
        // Resolvable<String>), visit directly.
        assert!(
            out.contains("ProvisionStep::Script { script, .. } => {"),
            "Script variant destructure:\n{out}"
        );
        assert!(
            out.contains("__visit(&__field_path, ResolvableField::Str(script))?;"),
            "Script visit:\n{out}"
        );
    }

    /// F2.7c — tagged enum variants with no walkable fields get a
    /// `_ => {}` skip arm rather than a destructure-and-walk arm.
    #[test]
    fn walker_skips_resolvable_free_tagged_variants() {
        let module = ModuleIR {
            schemas: Vec::new(),
            enums: Vec::new(),
            tagged_enums: vec![TaggedEnumIR {
                name: "Step".into(),
                source_file: "x.k".into(),
                source_line: 0,
                doc: String::new(),
                discriminator: "type".into(),
                shared_fields: Vec::new(),
                variants: vec![
                    TaggedEnumVariantIR {
                        rust_name: "Eager".into(),
                        kcl_literal: "eager".into(),
                        fields: vec![FieldIR {
                            name: "name".into(),
                            kind: FieldKind::Str,
                            optional: false,
                            has_default: false,
                        }],
                    },
                    TaggedEnumVariantIR {
                        rust_name: "Symbolic".into(),
                        kcl_literal: "symbolic".into(),
                        fields: vec![FieldIR {
                            name: "value".into(),
                            kind: FieldKind::Resolvable(Box::new(FieldKind::Str)),
                            optional: false,
                            has_default: false,
                        }],
                    },
                ],
            }],
        };
        let out = emit_rust_source(&module).expect("emit");
        // Eager arm: skipped.
        assert!(
            out.contains("Step::Eager { .. } => {}"),
            "Eager skipped:\n{out}"
        );
        // Symbolic arm: destructured and visited.
        assert!(
            out.contains("Step::Symbolic { value, .. } => {"),
            "Symbolic destructured:\n{out}"
        );
    }
}
