//! Emit Rust source text from a `Vec<SchemaIR>`.
//!
//! Generated code shape:
//!
//! ```text
//! // AUTO-GENERATED banner
//! #![allow(...)]
//!
//! mod _kcl_codegen_helpers { ... }  // small per-file helper module
//!
//! /// Generated from src/schemas/core.k (line 10)
//! pub struct Vm {
//!     pub name: String,
//!     pub memory_mb: i64,
//!     pub notes: Option<String>,
//! }
//!
//! impl TryFrom<&kcl_runtime::ValueRef> for Vm {
//!     type Error = String;
//!     fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {
//!         let name = _kcl_codegen_helpers::require(...)?;
//!         ...
//!         Ok(Vm { name, memory_mb, notes })
//!     }
//! }
//! ```
//!
//! The helper module is emitted once per output file and contains
//! the type-conversion primitives every TryFrom impl uses. The
//! per-schema TryFrom impls are short and explicit — each field maps
//! to one call into the helpers.

use crate::ir::{FieldIR, FieldKind, SchemaIR};
use crate::CodegenError;

const BANNER: &str = "\
// AUTO-GENERATED by kcl-rust-codegen — DO NOT EDIT BY HAND.
// Regenerate by re-running the codegen tool against the source KCL.

#![allow(clippy::derive_partial_eq_without_eq)]
#![allow(clippy::needless_question_mark)]
#![allow(non_snake_case)]
#![allow(dead_code)]

";

const HELPERS: &str = r##"
/// Helper functions used by the generated `TryFrom<&ValueRef>`
/// implementations. Emitted once per file; not part of the public
/// API. Kept in a private module so generated types don't pollute
/// the consumer's namespace.
mod _kcl_codegen_helpers {
    use kcl_runtime::ValueRef;

    pub fn from_int(v: &ValueRef) -> Result<i64, String> {
        if v.is_int() {
            Ok(v.as_int())
        } else {
            Err(format!("expected int, got {}", v.type_str()))
        }
    }
    pub fn from_float(v: &ValueRef) -> Result<f64, String> {
        if v.is_float() {
            Ok(v.as_float())
        } else if v.is_int() {
            Ok(v.as_int() as f64)
        } else {
            Err(format!("expected float, got {}", v.type_str()))
        }
    }
    pub fn from_bool(v: &ValueRef) -> Result<bool, String> {
        if v.is_bool() {
            Ok(v.as_bool())
        } else {
            Err(format!("expected bool, got {}", v.type_str()))
        }
    }
    pub fn from_str(v: &ValueRef) -> Result<String, String> {
        if v.is_str() {
            Ok(v.as_str())
        } else {
            Err(format!("expected str, got {}", v.type_str()))
        }
    }

    /// Read a required field from a schema-or-dict ValueRef.
    pub fn require<T, F>(
        v: &ValueRef,
        field: &str,
        parent: &str,
        conv: F,
    ) -> Result<T, String>
    where
        F: FnOnce(&ValueRef) -> Result<T, String>,
    {
        match v.dict_get_value(field) {
            Some(f) => conv(&f).map_err(|e| format!("{parent}.{field}: {e}")),
            None => Err(format!("{parent}.{field}: missing")),
        }
    }

    /// Read an optional field (`field?: T` in KCL) from a
    /// schema-or-dict ValueRef. Both `Value::undefined` and
    /// `Value::none` map to `None` per the D5 codegen mapping; an
    /// absent field also maps to `None` (defensive). Anything else
    /// runs through `conv`.
    pub fn optional<T, F>(
        v: &ValueRef,
        field: &str,
        parent: &str,
        conv: F,
    ) -> Result<Option<T>, String>
    where
        F: FnOnce(&ValueRef) -> Result<T, String>,
    {
        match v.dict_get_value(field) {
            None => Ok(None),
            Some(f) if f.is_undefined() || f.is_none() => Ok(None),
            Some(f) => conv(&f)
                .map(Some)
                .map_err(|e| format!("{parent}.{field}: {e}")),
        }
    }

    /// Convert a list `ValueRef` into a `Vec<T>` by applying `conv`
    /// to each element. Errors include the offending element index.
    pub fn from_list<T, F>(v: &ValueRef, mut conv: F) -> Result<Vec<T>, String>
    where
        F: FnMut(&ValueRef) -> Result<T, String>,
    {
        if !v.is_list() {
            return Err(format!("expected list, got {}", v.type_str()));
        }
        let list = v.as_list_ref();
        let mut out = Vec::with_capacity(list.values.len());
        for (i, item) in list.values.iter().enumerate() {
            out.push(conv(item).map_err(|e| format!("[{i}]: {e}"))?);
        }
        Ok(out)
    }

    /// Convert a dict `ValueRef` into a `HashMap<String, V>` (KCL
    /// dicts are str-keyed at the runtime layer) by applying `conv`
    /// to each value. Errors include the offending key.
    pub fn from_dict<V, F>(
        v: &ValueRef,
        mut conv: F,
    ) -> Result<std::collections::HashMap<String, V>, String>
    where
        F: FnMut(&ValueRef) -> Result<V, String>,
    {
        if !v.is_dict() && !v.is_schema() {
            return Err(format!("expected dict, got {}", v.type_str()));
        }
        let dict = v.as_dict_ref();
        let mut out = std::collections::HashMap::with_capacity(dict.values.len());
        for (k, item) in dict.values.iter() {
            out.insert(
                k.clone(),
                conv(item).map_err(|e| format!("[{k:?}]: {e}"))?,
            );
        }
        Ok(out)
    }
}

"##;

/// Emit a single Rust source string for the given `SchemaIR` list.
pub(crate) fn emit_rust_source(schemas: &[SchemaIR]) -> Result<String, CodegenError> {
    let mut out = String::with_capacity(BANNER.len() + HELPERS.len() + 1024);
    out.push_str(BANNER);
    out.push_str(HELPERS);
    for schema in schemas {
        emit_struct(&mut out, schema);
        emit_try_from(&mut out, schema);
    }
    Ok(out)
}

fn emit_struct(out: &mut String, schema: &SchemaIR) {
    if !schema.doc.is_empty() {
        for line in schema.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "/// Generated from `{}` (line {})\n",
        schema.source_file, schema.source_line
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub struct {} {{\n", schema.name));
    for field in &schema.fields {
        if field.has_default {
            out.push_str(&format!(
                "    /// Has a default value in the source schema; the KCL VM\n",
            ));
            out.push_str(
                "    /// populates it during evaluation, so this field is\n",
            );
            out.push_str("    /// always present in the resulting `ValueRef`.\n");
        }
        let rust_ty = field.kind.to_rust_type();
        let rust_ty = if field.optional {
            format!("Option<{rust_ty}>")
        } else {
            rust_ty
        };
        out.push_str(&format!("    pub {}: {},\n", field.name, rust_ty));
    }
    out.push_str("}\n\n");
}

fn emit_try_from(out: &mut String, schema: &SchemaIR) {
    let name = &schema.name;
    out.push_str(&format!(
        "impl TryFrom<&kcl_runtime::ValueRef> for {name} {{\n"
    ));
    out.push_str("    type Error = String;\n");
    out.push_str(
        "    /// In a well-formed deployment where (a) codegen was run against the same\n",
    );
    out.push_str(
        "    /// schema source the VM was given, and (b) the VM successfully evaluated the\n",
    );
    out.push_str(
        "    /// user program against that schema, the `Err` branch is unreachable: the\n",
    );
    out.push_str(
        "    /// VM would have rejected the input before producing a `ValueRef` that fails\n",
    );
    out.push_str(
        "    /// this conversion. The `Result` is a typed seatbelt against codegen drift\n",
    );
    out.push_str(
        "    /// and VM bugs, not a control-flow surface — prefer `.expect(\"VM produced\n",
    );
    out.push_str(
        "    /// schema-conformant value\")` over propagating the error.\n",
    );
    out.push_str("    fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {\n");
    out.push_str("        if !v.is_dict() && !v.is_schema() {\n");
    out.push_str(&format!(
        "            return Err(format!(\"expected {name} dict/schema, got {{}}\", v.type_str()));\n"
    ));
    out.push_str("        }\n");
    for field in &schema.fields {
        emit_field_read(out, name, field);
    }
    out.push_str(&format!("        Ok({name} {{\n"));
    for field in &schema.fields {
        out.push_str(&format!("            {},\n", field.name));
    }
    out.push_str("        })\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn emit_field_read(out: &mut String, parent: &str, field: &FieldIR) {
    let conv = emit_conv_closure(&field.kind);
    if field.optional {
        out.push_str(&format!(
            "        let {} = _kcl_codegen_helpers::optional(v, \"{}\", \"{}\", {})?;\n",
            field.name, field.name, parent, conv
        ));
    } else {
        out.push_str(&format!(
            "        let {} = _kcl_codegen_helpers::require(v, \"{}\", \"{}\", {})?;\n",
            field.name, field.name, parent, conv
        ));
    }
}

/// Emit a closure expression that, given a `&ValueRef`, converts it
/// to the field's Rust type. Recursive: lists/dicts compose their
/// item/value conversion.
fn emit_conv_closure(kind: &FieldKind) -> String {
    match kind {
        FieldKind::Int => "_kcl_codegen_helpers::from_int".to_string(),
        FieldKind::Float => "_kcl_codegen_helpers::from_float".to_string(),
        FieldKind::Bool => "_kcl_codegen_helpers::from_bool".to_string(),
        FieldKind::Str => "_kcl_codegen_helpers::from_str".to_string(),
        FieldKind::List(inner) => {
            let inner_conv = emit_conv_closure(inner);
            format!("|f: &kcl_runtime::ValueRef| _kcl_codegen_helpers::from_list(f, {inner_conv})")
        }
        FieldKind::Dict(_key, val) => {
            // KCL dicts are str-keyed at the runtime layer regardless
            // of the declared key type; we currently only emit the
            // value-conversion closure and rely on the helper to
            // surface String keys. Non-String declared key types
            // would be flagged in step 5 if the consumer needs them.
            let val_conv = emit_conv_closure(val);
            format!("|f: &kcl_runtime::ValueRef| _kcl_codegen_helpers::from_dict(f, {val_conv})")
        }
        FieldKind::Schema(name) => {
            format!(
                "|f: &kcl_runtime::ValueRef| <{name} as TryFrom<&kcl_runtime::ValueRef>>::try_from(f)"
            )
        }
        FieldKind::Unsupported(label) => {
            // Should have been caught during IR construction; emit
            // a compile-error sentinel just in case.
            format!("compile_error!(\"unsupported field kind: {label}\")")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::FieldIR;

    fn schema_ir_for(name: &str, fields: Vec<FieldIR>) -> SchemaIR {
        SchemaIR {
            name: name.to_string(),
            source_file: "test.k".to_string(),
            source_line: 0,
            fields,
            doc: String::new(),
        }
    }

    #[test]
    fn emit_primitive_struct() {
        let schema = schema_ir_for(
            "Vm",
            vec![
                FieldIR {
                    name: "name".into(),
                    kind: FieldKind::Str,
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "memory_mb".into(),
                    kind: FieldKind::Int,
                    optional: false,
                    has_default: true,
                },
                FieldIR {
                    name: "notes".into(),
                    kind: FieldKind::Str,
                    optional: true,
                    has_default: false,
                },
            ],
        );
        let out = emit_rust_source(&[schema]).expect("emit");
        assert!(out.contains("pub struct Vm {"));
        assert!(out.contains("pub name: String,"));
        assert!(out.contains("pub memory_mb: i64,"));
        assert!(out.contains("pub notes: Option<String>,"));
        assert!(out.contains(
            "impl TryFrom<&kcl_runtime::ValueRef> for Vm"
        ));
        assert!(out.contains("_kcl_codegen_helpers::require(v, \"name\""));
        assert!(out.contains("_kcl_codegen_helpers::optional(v, \"notes\""));
    }

    #[test]
    fn emit_list_of_nested_schema() {
        let schemas = vec![
            schema_ir_for(
                "Disk",
                vec![FieldIR {
                    name: "size_gb".into(),
                    kind: FieldKind::Int,
                    optional: false,
                    has_default: false,
                }],
            ),
            schema_ir_for(
                "Vm",
                vec![FieldIR {
                    name: "disks".into(),
                    kind: FieldKind::List(Box::new(FieldKind::Schema("Disk".into()))),
                    optional: false,
                    has_default: false,
                }],
            ),
        ];
        let out = emit_rust_source(&schemas).expect("emit");
        assert!(out.contains("pub disks: Vec<Disk>,"));
        assert!(out.contains(
            "_kcl_codegen_helpers::from_list(f, |f: &kcl_runtime::ValueRef| <Disk as TryFrom"
        ));
    }
}
