//! Emit Rust source text from a [`ModuleIR`].

use crate::ir::{
    EnumIR, FieldIR, FieldKind, ModuleIR, SchemaIR, TaggedEnumIR, escape_rust_keyword,
    pascal_case,
};
use crate::CodegenError;

const BANNER: &str = "\
// AUTO-GENERATED by kcl-rust-codegen — DO NOT EDIT BY HAND.
// Regenerate by re-running the codegen tool against the source KCL.
//
// Consumers that include! this file may want to wrap the include in
// a module like:
//   mod kcl_types {
//       #![allow(non_snake_case, dead_code)]
//       include!(concat!(env!(\"OUT_DIR\"), \"/generated_types.rs\"));
//   }
// so per-file lints don't bleed into the rest of their crate. The
// codegen tool intentionally does not emit #![...] attributes at the
// file root since include! places this content inside whatever scope
// the consumer chose.

";

const HELPERS: &str = r##"
/// Helper functions used by the generated `TryFrom<&ValueRef>`
/// implementations.
mod _kcl_codegen_helpers {
    use kcl_runtime::ValueRef;

    pub fn from_int(v: &ValueRef) -> Result<i64, String> {
        if v.is_int() {
            Ok(v.as_int())
        } else {
            Err(format!("expected int, got {}", v.type_str()))
        }
    }
    pub fn from_float(v: &ValueRef) -> Result<f64, String> {
        if v.is_float() {
            Ok(v.as_float())
        } else if v.is_int() {
            Ok(v.as_int() as f64)
        } else {
            Err(format!("expected float, got {}", v.type_str()))
        }
    }
    pub fn from_bool(v: &ValueRef) -> Result<bool, String> {
        if v.is_bool() {
            Ok(v.as_bool())
        } else {
            Err(format!("expected bool, got {}", v.type_str()))
        }
    }
    pub fn from_str(v: &ValueRef) -> Result<String, String> {
        if v.is_str() {
            Ok(v.as_str())
        } else {
            Err(format!("expected str, got {}", v.type_str()))
        }
    }

    pub fn require<T, F>(
        v: &ValueRef,
        field: &str,
        parent: &str,
        conv: F,
    ) -> Result<T, String>
    where
        F: FnOnce(&ValueRef) -> Result<T, String>,
    {
        match v.dict_get_value(field) {
            Some(f) => conv(&f).map_err(|e| format!("{parent}.{field}: {e}")),
            None => Err(format!("{parent}.{field}: missing")),
        }
    }

    pub fn optional<T, F>(
        v: &ValueRef,
        field: &str,
        parent: &str,
        conv: F,
    ) -> Result<Option<T>, String>
    where
        F: FnOnce(&ValueRef) -> Result<T, String>,
    {
        match v.dict_get_value(field) {
            None => Ok(None),
            Some(f) if f.is_undefined() || f.is_none() => Ok(None),
            Some(f) => conv(&f)
                .map(Some)
                .map_err(|e| format!("{parent}.{field}: {e}")),
        }
    }

    pub fn from_list<T, F>(v: &ValueRef, mut conv: F) -> Result<Vec<T>, String>
    where
        F: FnMut(&ValueRef) -> Result<T, String>,
    {
        if !v.is_list() {
            return Err(format!("expected list, got {}", v.type_str()));
        }
        let list = v.as_list_ref();
        let mut out = Vec::with_capacity(list.values.len());
        for (i, item) in list.values.iter().enumerate() {
            out.push(conv(item).map_err(|e| format!("[{i}]: {e}"))?);
        }
        Ok(out)
    }

    pub fn from_dict<V, F>(
        v: &ValueRef,
        mut conv: F,
    ) -> Result<std::collections::HashMap<String, V>, String>
    where
        F: FnMut(&ValueRef) -> Result<V, String>,
    {
        if !v.is_dict() && !v.is_schema() {
            return Err(format!("expected dict, got {}", v.type_str()));
        }
        let dict = v.as_dict_ref();
        let mut out = std::collections::HashMap::with_capacity(dict.values.len());
        for (k, item) in dict.values.iter() {
            out.insert(
                k.clone(),
                conv(item).map_err(|e| format!("[{k:?}]: {e}"))?,
            );
        }
        Ok(out)
    }
}

"##;

pub(crate) fn emit_rust_source(module: &ModuleIR) -> Result<String, CodegenError> {
    let mut out = String::with_capacity(BANNER.len() + HELPERS.len() + 1024);
    out.push_str(BANNER);
    out.push_str(HELPERS);
    for e in &module.enums {
        emit_enum(&mut out, e);
    }
    for tagged in &module.tagged_enums {
        emit_tagged_enum(&mut out, tagged);
        emit_tagged_enum_try_from(&mut out, tagged);
    }
    for schema in &module.schemas {
        emit_struct(&mut out, schema);
        emit_try_from(&mut out, schema);
    }
    Ok(out)
}

fn emit_enum(out: &mut String, e: &EnumIR) {
    out.push_str(&format!(
        "/// Generated from {} — lifted from a KCL string-literal union.\n",
        e.origin
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n");
    out.push_str(&format!("pub enum {} {{\n", e.rust_name));
    for variant in &e.variants {
        out.push_str(&format!("    /// KCL source literal: {variant:?}\n"));
        out.push_str(&format!("    {},\n", pascal_case(variant)));
    }
    out.push_str("}\n\n");

    // TryFrom<&ValueRef>: matches on the string content; rejects
    // anything that isn't one of the declared literals.
    out.push_str(&format!(
        "impl TryFrom<&kcl_runtime::ValueRef> for {} {{\n",
        e.rust_name
    ));
    out.push_str("    type Error = String;\n");
    out.push_str("    fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {\n");
    out.push_str("        if !v.is_str() {\n");
    out.push_str(&format!(
        "            return Err(format!(\"expected str for {}, got {{}}\", v.type_str()));\n",
        e.rust_name
    ));
    out.push_str("        }\n");
    out.push_str("        match v.as_str().as_str() {\n");
    for variant in &e.variants {
        out.push_str(&format!(
            "            {:?} => Ok({}::{}),\n",
            variant,
            e.rust_name,
            pascal_case(variant)
        ));
    }
    // Build the expected-list literal with each variant wrapped in
    // escaped quotes so the generated Rust source compiles. (Naively
    // interpolating `{:?}` on a Vec<String> produces unescaped
    // double-quotes inside the surrounding string literal.)
    let expected_list = e
        .variants
        .iter()
        .map(|v| format!("\\\"{v}\\\""))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "            other => Err(format!(\"unexpected {} literal {{other:?}}; expected one of [{expected_list}]\")),\n",
        e.rust_name
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn emit_struct(out: &mut String, schema: &SchemaIR) {
    if !schema.doc.is_empty() {
        for line in schema.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "/// Generated from `{}` (line {})\n",
        schema.source_file, schema.source_line
    ));
    // PartialEq on f64 is NaN-aware: `f64::NAN != f64::NAN`. For
    // schemas with float fields this is the standard Rust behaviour,
    // but worth flagging in the generated rustdoc so consumers
    // aren't surprised when two `Vm`s with NaN field values compare
    // unequal. (Future evolution: conditional derive or custom impl
    // — out of MVP scope; tracked under Phase 4B.)
    let has_float = schema.fields.iter().any(|f| f.kind.contains_float());
    if has_float {
        out.push_str(
            "/// **Note:** this type contains `f64` field(s); the derived\n",
        );
        out.push_str(
            "/// `PartialEq` is NaN-aware (`f64::NAN != f64::NAN`). Two\n",
        );
        out.push_str(
            "/// instances with NaN field values will compare unequal.\n",
        );
    }
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub struct {} {{\n", schema.name));
    for field in &schema.fields {
        if field.has_default {
            out.push_str(
                "    /// Has a default value in the source schema; the KCL VM populates it\n",
            );
            out.push_str(
                "    /// during evaluation, so this field is always present in the\n",
            );
            out.push_str("    /// resulting `ValueRef`.\n");
        }
        let rust_ty = field.kind.to_rust_type();
        let rust_ty = if field.optional {
            format!("Option<{rust_ty}>")
        } else {
            rust_ty
        };
        out.push_str(&format!(
            "    pub {}: {},\n",
            escape_rust_keyword(&field.name),
            rust_ty
        ));
    }
    out.push_str("}\n\n");
}

fn emit_try_from(out: &mut String, schema: &SchemaIR) {
    let name = &schema.name;
    out.push_str(&format!(
        "impl TryFrom<&kcl_runtime::ValueRef> for {name} {{\n"
    ));
    out.push_str("    type Error = String;\n");
    out.push_str(
        "    /// In a well-formed deployment where (a) codegen was run against the same\n",
    );
    out.push_str(
        "    /// schema source the VM was given, and (b) the VM successfully evaluated the\n",
    );
    out.push_str(
        "    /// user program against that schema, the `Err` branch is unreachable: the\n",
    );
    out.push_str(
        "    /// VM would have rejected the input before producing a `ValueRef` that fails\n",
    );
    out.push_str(
        "    /// this conversion. The `Result` is a typed seatbelt against codegen drift\n",
    );
    out.push_str(
        "    /// and VM bugs, not a control-flow surface — prefer `.expect(\"VM produced\n",
    );
    out.push_str(
        "    /// schema-conformant value\")` over propagating the error.\n",
    );
    out.push_str("    fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {\n");
    out.push_str("        if !v.is_dict() && !v.is_schema() {\n");
    out.push_str(&format!(
        "            return Err(format!(\"expected {name} dict/schema, got {{}}\", v.type_str()));\n"
    ));
    out.push_str("        }\n");
    for field in &schema.fields {
        emit_field_read(out, name, field);
    }
    out.push_str(&format!("        Ok({name} {{\n"));
    for field in &schema.fields {
        out.push_str(&format!("            {},\n", escape_rust_keyword(&field.name)));
    }
    out.push_str("        })\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

/// Emit a Rust `enum TaggedX { ... }` definition from a
/// [`TaggedEnumIR`]. Each variant has its assigned fields plus the
/// `shared_fields` from the parent. The discriminator field itself
/// is NOT emitted — the variant tag encodes it.
fn emit_tagged_enum(out: &mut String, tagged: &TaggedEnumIR) {
    if !tagged.doc.is_empty() {
        for line in tagged.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "/// Generated from `{}` (line {}) — tagged enum lifted via `# @rust: tagged_enum(discriminator = {:?})`.\n",
        tagged.source_file, tagged.source_line, tagged.discriminator,
    ));
    let has_float = tagged
        .variants
        .iter()
        .flat_map(|v| v.fields.iter())
        .chain(tagged.shared_fields.iter())
        .any(|f| f.kind.contains_float());
    if has_float {
        out.push_str(
            "/// **Note:** this enum contains `f64` field(s); the derived\n",
        );
        out.push_str(
            "/// `PartialEq` is NaN-aware (`f64::NAN != f64::NAN`).\n",
        );
    }
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {} {{\n", tagged.name));
    for variant in &tagged.variants {
        out.push_str(&format!(
            "    /// KCL discriminator literal: {:?}\n",
            variant.kcl_literal,
        ));
        out.push_str(&format!("    {} {{\n", variant.rust_name));
        // Variant-assigned fields first, then shared fields. Stable
        // ordering matters for pattern-match ergonomics — variant
        // fields are what's "interesting" per variant.
        for field in &variant.fields {
            emit_variant_field_decl(out, field);
        }
        for field in &tagged.shared_fields {
            emit_variant_field_decl(out, field);
        }
        out.push_str("    },\n");
    }
    out.push_str("}\n\n");
}

fn emit_variant_field_decl(out: &mut String, field: &FieldIR) {
    if field.has_default {
        out.push_str(
            "        /// Has a default value in the source schema; populated by the KCL VM.\n",
        );
    }
    let rust_ty = field.kind.to_rust_type();
    let rust_ty = if field.optional {
        format!("Option<{rust_ty}>")
    } else {
        rust_ty
    };
    out.push_str(&format!(
        "        {}: {},\n",
        escape_rust_keyword(&field.name),
        rust_ty,
    ));
}

/// Emit `impl TryFrom<&ValueRef> for TaggedX`. Reads the
/// discriminator field, dispatches on its string value, reads each
/// variant's assigned + shared fields, constructs the matching
/// variant.
fn emit_tagged_enum_try_from(out: &mut String, tagged: &TaggedEnumIR) {
    let name = &tagged.name;
    let discriminator = &tagged.discriminator;

    out.push_str(&format!(
        "impl TryFrom<&kcl_runtime::ValueRef> for {name} {{\n"
    ));
    out.push_str("    type Error = String;\n");
    out.push_str(
        "    /// In a well-formed deployment where (a) codegen was run against the same\n",
    );
    out.push_str(
        "    /// schema source the VM was given, and (b) the VM successfully evaluated the\n",
    );
    out.push_str(
        "    /// user program against that schema (including its `check:` block predicates\n",
    );
    out.push_str(
        "    /// enforcing per-variant required fields), the `Err` branch is unreachable.\n",
    );
    out.push_str("    fn try_from(v: &kcl_runtime::ValueRef) -> Result<Self, Self::Error> {\n");
    out.push_str("        if !v.is_dict() && !v.is_schema() {\n");
    out.push_str(&format!(
        "            return Err(format!(\"expected {name} dict/schema, got {{}}\", v.type_str()));\n"
    ));
    out.push_str("        }\n");
    // Read discriminator string from the dict.
    out.push_str(&format!(
        "        let __disc = _kcl_codegen_helpers::require(v, \"{discriminator}\", \"{name}\", _kcl_codegen_helpers::from_str)?;\n"
    ));
    out.push_str("        match __disc.as_str() {\n");
    for variant in &tagged.variants {
        let variant_parent = format!("{}::{}", name, variant.rust_name);
        out.push_str(&format!("            {:?} => {{\n", variant.kcl_literal));
        for field in &variant.fields {
            emit_variant_field_read(out, &variant_parent, field);
        }
        for field in &tagged.shared_fields {
            emit_variant_field_read(out, &variant_parent, field);
        }
        out.push_str(&format!(
            "                Ok({}::{} {{\n",
            name, variant.rust_name,
        ));
        for field in &variant.fields {
            out.push_str(&format!(
                "                    {},\n",
                escape_rust_keyword(&field.name),
            ));
        }
        for field in &tagged.shared_fields {
            out.push_str(&format!(
                "                    {},\n",
                escape_rust_keyword(&field.name),
            ));
        }
        out.push_str("                })\n");
        out.push_str("            }\n");
    }
    let expected_list = tagged
        .variants
        .iter()
        .map(|v| format!("\\\"{}\\\"", v.kcl_literal))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "            other => Err(format!(\"unexpected {name}.{discriminator} literal {{other:?}}; expected one of [{expected_list}]\")),\n"
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn emit_variant_field_read(out: &mut String, parent: &str, field: &FieldIR) {
    let conv = emit_conv_closure(&field.kind);
    let binding = escape_rust_keyword(&field.name);
    let indent = "                ";
    if field.optional {
        out.push_str(&format!(
            "{indent}let {binding} = _kcl_codegen_helpers::optional(v, \"{}\", \"{}\", {})?;\n",
            field.name, parent, conv,
        ));
    } else {
        out.push_str(&format!(
            "{indent}let {binding} = _kcl_codegen_helpers::require(v, \"{}\", \"{}\", {})?;\n",
            field.name, parent, conv,
        ));
    }
}

fn emit_field_read(out: &mut String, parent: &str, field: &FieldIR) {
    let conv = emit_conv_closure(&field.kind);
    let binding = escape_rust_keyword(&field.name);
    if field.optional {
        out.push_str(&format!(
            "        let {} = _kcl_codegen_helpers::optional(v, \"{}\", \"{}\", {})?;\n",
            binding, field.name, parent, conv
        ));
    } else {
        out.push_str(&format!(
            "        let {} = _kcl_codegen_helpers::require(v, \"{}\", \"{}\", {})?;\n",
            binding, field.name, parent, conv
        ));
    }
}

fn emit_conv_closure(kind: &FieldKind) -> String {
    match kind {
        FieldKind::Int => "_kcl_codegen_helpers::from_int".to_string(),
        FieldKind::Float => "_kcl_codegen_helpers::from_float".to_string(),
        FieldKind::Bool => "_kcl_codegen_helpers::from_bool".to_string(),
        FieldKind::Str => "_kcl_codegen_helpers::from_str".to_string(),
        FieldKind::List(inner) => {
            let inner_conv = emit_conv_closure(inner);
            format!("|f: &kcl_runtime::ValueRef| _kcl_codegen_helpers::from_list(f, {inner_conv})")
        }
        FieldKind::Dict(_key, val) => {
            let val_conv = emit_conv_closure(val);
            format!("|f: &kcl_runtime::ValueRef| _kcl_codegen_helpers::from_dict(f, {val_conv})")
        }
        FieldKind::Schema(name) => {
            format!(
                "|f: &kcl_runtime::ValueRef| <{name} as TryFrom<&kcl_runtime::ValueRef>>::try_from(f)"
            )
        }
        FieldKind::StrEnum(name) => {
            format!(
                "|f: &kcl_runtime::ValueRef| <{name} as TryFrom<&kcl_runtime::ValueRef>>::try_from(f)"
            )
        }
        FieldKind::Unsupported(label) => {
            format!("compile_error!(\"unsupported field kind: {label}\")")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::FieldIR;

    fn schema_ir_for(name: &str, fields: Vec<FieldIR>) -> SchemaIR {
        SchemaIR {
            name: name.to_string(),
            source_file: "test.k".to_string(),
            source_line: 0,
            fields,
            doc: String::new(),
            annotations: Default::default(),
        }
    }

    fn module_with_schemas(schemas: Vec<SchemaIR>) -> ModuleIR {
        ModuleIR {
            schemas,
            enums: Vec::new(),
            tagged_enums: Vec::new(),
        }
    }

    #[test]
    fn emit_primitive_struct() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Vm",
            vec![
                FieldIR {
                    name: "name".into(),
                    kind: FieldKind::Str,
                    optional: false,
                    has_default: false,
                },
                FieldIR {
                    name: "memory_mb".into(),
                    kind: FieldKind::Int,
                    optional: false,
                    has_default: true,
                },
                FieldIR {
                    name: "notes".into(),
                    kind: FieldKind::Str,
                    optional: true,
                    has_default: false,
                },
            ],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(out.contains("pub struct Vm {"));
        assert!(out.contains("pub name: String,"));
        assert!(out.contains("pub memory_mb: i64,"));
        assert!(out.contains("pub notes: Option<String>,"));
        assert!(out.contains("impl TryFrom<&kcl_runtime::ValueRef> for Vm"));
    }

    #[test]
    fn emit_str_enum_and_field() {
        let mut module = module_with_schemas(vec![schema_ir_for(
            "TestAssertion",
            vec![FieldIR {
                name: "type".into(),
                kind: FieldKind::StrEnum("TestAssertionType".into()),
                optional: false,
                has_default: false,
            }],
        )]);
        module.enums.push(EnumIR {
            rust_name: "TestAssertionType".into(),
            variants: vec!["command".into(), "service".into(), "port".into()],
            origin: "TestAssertion.type".into(),
        });
        let out = emit_rust_source(&module).expect("emit");
        // Enum definition
        assert!(out.contains("pub enum TestAssertionType {"));
        assert!(out.contains("    Command,"));
        assert!(out.contains("    Service,"));
        assert!(out.contains("    Port,"));
        // Enum TryFrom matches the literals
        assert!(out.contains("\"command\" => Ok(TestAssertionType::Command),"));
        // Struct field uses the enum type
        assert!(out.contains("pub r#type: TestAssertionType,"));
        // Struct TryFrom delegates to enum's TryFrom
        assert!(out.contains(
            "<TestAssertionType as TryFrom<&kcl_runtime::ValueRef>>::try_from(f)"
        ));
    }

    #[test]
    fn escape_rust_keyword_field_names() {
        let module = module_with_schemas(vec![schema_ir_for(
            "Foo",
            vec![FieldIR {
                name: "type".into(),
                kind: FieldKind::Str,
                optional: false,
                has_default: false,
            }],
        )]);
        let out = emit_rust_source(&module).expect("emit");
        assert!(out.contains("pub r#type: String,"));
        assert!(out.contains("let r#type = _kcl_codegen_helpers::require(v, \"type\""));
    }
}
